name: Test Action

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: | 
          date
          echo "Hello GitHub Actions!"
       
